### PR TITLE
add stdin option, write to stdout in python 2/3, handle remote urls

### PR DESCRIPTION
**Pull request by l3thal**
adds ability to convert files with remote input url, 
checks python version before writing to stdout and uses buffered write for python 3 and direct write for earlier versions,
adds stdin option using private:stream
still works with regular file input/output as well

##### -r or --remote option to use remote url.
```
root@app0:~# unoconv -r --stdout -f html http://fqdn.com/sample.docx
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
...
```
##### --stdin option to read input from stdin. 
```
root@app0:~# cat sample.docx | unoconv --stdin --stdout -f html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
...
```

### CODE REVIEW

**Comment by ashaffer** [comment]
+1 for stdin

**Comment by pataquets** [comment]
Cross-referencing. Fixes #35.

**Comment by danmilon** [comment]
+1 for this over #180. better implementation.

**Comment by thenadz** [comment]
Is the remote flag even necessary? Could be implicitly determined at runtime.

Also, definitely +1 for accepting stdin and remote files.

**Comment by dagwieers** [comment]
Alright, the patch did not merge cleanly. Here's what I did 87cf4a22822e8d4e4d16deaa85e7639a054ffc8c:

 - I retained the --stdin stuff
 - I removed the -r/--remote option, but kept the functionality (so it should work implicitly (please test :-))
 - I did not retain the buffered output (python 2/3) because --stdout failed to work on python 2.7  (RHEL6)

For the last item, I think the version check fails on python 2.7. So if you find/fix this, I'll merge that pull request.

Please test and let me know if there are any loose ends (or major fuck-ups). Reopen if needed !

**Comment by dagwieers** [comment]
BTW @l3thal I retained you as the author for the commit, I hope you don't mind.
Thanks for your contributions and sorry for the delay.

**Comment by dagwieers** [comment]
PS Can we do #175 for the python3 write ?

**Comment by protist** [comment]
This doesn't work for me. I'm happy to open a new issue if required. Firstly, I get the following error in all test cases, although the file is produced perfectly for this example.
```
$ echo 'foo' | unoconv --stdin -o test.pdf
:1: parser error : Document is empty
foo
^
```

However, in some cases, the output will be garbled with pipes, but convert fine when running directly with `unoconv test.txt`. For example, the following file:

>1→foo
>2→foo
>3→foo
>4→foo
>5→foo
>6→foo
>7→foo
>8→foo
>9→foo
>10→foo

Using a pipe
```
$ cat test | unoconv --stdin -o test.pdf
:1: parser error : Document is empty
1→foo
^
```
Produces a pdf that only shows every second line, misses the `→` characters, and strikeouts most of the document, as below.

>1~~foo
>3foo
>5foo
>7foo
>9foo~~

**Comment by hugleo** [comment]
Didn't working for me either:

cat test.odt | unoconv --stdin -f pdf
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1185, in main
    inputfn = sys.stdin.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 15: invalid continuation byte

**Comment by protist** [comment]
Oh yeah, I haven't used this for a while. I'm getting similar errors now.
```
$ echo 'foo' | unoconv --stdin -o test.pdf

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1275, in <module>
    main()
  File "/usr/bin/unoconv", line 1187, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 892, in convert
    inputStream.initialize((uno.ByteSequence(inputfn),))
  File "/usr/lib/python3.6/site-packages/uno.py", line 279, in __init__
    raise TypeError("Expected bytes object or ByteSequence, got %s instead." % type(value))
TypeError: Expected bytes object or ByteSequence, got <class 'str'> instead.
```

**Comment by hugleo** [comment]
I managed to make it work for my odt file. Edited the file /usr/bin/unoconv line 1185 adding sys.stdin = sys.stdin.detach()

`        if op.stdin:
            sys.stdin = sys.stdin.detach()
            inputfn = sys.stdin.read()
            convertor = Convertor()
            convertor.convert(inputfn)
`
and convert with:

`
cat ./test.odt | unoconv --stdin --stdout -f pdf > test.pdf`

**Comment by protist** [comment]
That works now for me too, using `echo 'foo' | unoconv --stdin -o test.pdf`.

Also, I get no error in my example file [above](https://github.com/dagwieers/unoconv/pull/203#issuecomment-174805263), regardless of which format I use.
```
<test unoconv --stdin -o test.pdf
unoconv test
```
However, now both of the files are incorrect, both with the strikeouts as listed above. Well, I suppose the errors are consistent now at least! :confused:

**Comment by hugleo** [comment]
I forced decode  to a text like:

`      if op.stdin:
            inputfn = sys.stdin.buffer.raw.read().decode(encoding='UTF-8')
            convertor = Convertor()
            convertor.convert(inputfn)
`

echo 'test' | unoconv --stdin -f pdf 
:1: parser error : Document is empty
test
^
:1: parser error : Document is empty
test
^
:1: parser error : Document is empty
test
^

at least generate a pdf with test text :D

**Pull request closed without merging**
