### PR TITLE
Add -F|--field to update user-defined fields before exporting document

### PR DESCRIPTION
**Pull request by raphink**
This PR adds a new option to update user defined fields before exporting the document, e.g.:

    $ unoconv -f pdf -F Client_Name="Advanced Augeas" -F Document_Type="Student Guide" -F Document_Title="for Systems Administrators" -F Document_Date="`date --iso`" -F Document_Last_Version="2.1" augeas_cover.odt

### CODE REVIEW

**Comment by raphink** [comment]
@skywinder any news on this?

**Comment by skywinder** [comment]
Hi! Thanks! It looks good, it's need to be tested before merge.

**Comment by raphink** [comment]
No problem. I've been using it in production on a regular basis for more than a year. I welcome any further testing :-)

**Comment by dagwieers** [comment]
@raphink I do like the functionality, but I was concerned that it was very specific to certain document types and therefore was better placed in a plugin (once we have the plugin-system).

But looking at it again, I think it is fine. If a document format does not support it, it doesn't cause any harm either. Maybe the documentation could hint to where it works/doesn't work ?

But I am merging this right away, I can see some use for my own :-)

**Comment by dagwieers** [comment]
Thanks !

**Pull request merged**
