### PR TITLE
All tests fail on macOS

### PR DESCRIPTION
**Pull request by regebro**
Disable those tests temporarily, as running them is pointless until somebody can fix the tests.

### CODE REVIEW

**Comment by dagwieers** [comment]
Well, if you disable them there's no longer an incentive to fix the tests.
So I am not in favor of avoiding doing the right thing.
Maybe we should ask some of the MacOSX people from the past to look into it ?

**Comment by regebro** [comment]
Well, I can't fix it, I don't have OS X, and you don't have time. 

By running a whole bunch of slow tests that fail we also get throttled by Travis, at one point it took 10-12 hours for the tests to run, which is annoying.

But sure, we can maybe ask for help first.

**Comment by regebro** [comment]
OK, this weekend I dug out my old Macbook, and installed an old OS X and an old Libreoffice and homebrew, and ran the tests.

They work file for some output formats, but for any format that uses XML, you get an error.

Opening LibreOffice and saving to any of the failing format will ALSO fail.

Hence, this is not a uniconv fault, it's a LibreOffice bug on macOS. I think we need to avoid docbook, mediawiki, ooxml, uot and xhtml when running tests on macs. Not sure of the best way of doing that.

**Comment by regebro** [comment]
Closing in favor of #424

**Pull request closed without merging**
