### PR TITLE
Attempting to fix the failures on macOS

### PR DESCRIPTION
**Pull request by regebro**
This should at least give new errors.

### CODE REVIEW

**Comment by regebro** [comment]
Locally on OS X 10.5 I still have problems converting to any XML format. Let's see how Travis done.

**Comment by regebro** [comment]
Yes, the XML formats don't work on macOS (it's not a unoconv issue, it's LibreOffice), and it seems later versions of the macOS releases has a broken uno library or something (see #399).

Possibly the solution is to compile LibreOffice for use on mac instead of using the binaries.

**Comment by jalevin** [comment]
I'm still having issues getting to run on OSX. What version of OSX/ LibreOffice/ Unoconv were you able to get everything working with?

**Comment by regebro** [comment]
OS X 10.5, I don't remember the Libre Office version, but ancient.

**Comment by workmanw** [comment]
@regebro Thanks for this fix, it solved the problem for me. Any chance of releasing an 0.8.3 so I don't have to install from master when building my docker containers?

**Pull request merged**
