### PR TITLE
Fix for Python 3 to read binary data from stdin

### PR DESCRIPTION
**Pull request by kaysersoze**
Reference: https://docs.python.org/3.1/library/sys.html#sys.stdin

### CODE REVIEW

**Comment by kaysersoze** [comment]
This fixes an issue I encountered when trying to pass a file in via stdin. 
```
Traceback (most recent call last):
  File "/usr/local/bin/unoconv", line 1349, in <module>
    main()
  File "/usr/local/bin/unoconv", line 1259, in main
    inputfn = sys.stdin.read()
  File "/Applications/LibreOffice.app/Contents/MacOS/LibreOfficePython.framework/Versions/3.3/lib/python3.3/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 14: ordinal not in range(128)
```

**Comment by dagwieers** [comment]
I am personally not for if-else constructs on a single line.
In my opinion they break readability (but maybe I am getting old ;-))

If you don't want/know how to update the PR, let me know and I will merge and fix it myself.

Thanks !

**Comment by kaysersoze** [comment]
@dagwieers I've restructured the ternary into an if-else. Let me know if that looks good.

**Comment by dagwieers** [comment]
Perfect, thanks ! Merged !

**Pull request merged**
